#pragma once
#include <iostream>
#include <fstream>
#include <sstream>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <shaders/shader.h>
#include <objloader.h>
#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>
